### PR TITLE
Adding kMBLocationManagerNotificationAuthorizationChangedName

### PR DESCRIPTION
**Pull request by marcelofabri**

### CODE REVIEW

**Comment by marcelofabri** [comment]
Have you gotten the chance to take a look at this, @MatejBalantic?

**Comment by MatejBalantic** [comment]
Sorry for the delay, I don't know how I missed this. Thanks for the improvement
:+1:

**Comment by marcelofabri** [comment]
No problem! Thanks for creating this :+1:

**Comment by marcelofabri** [comment]
Could you also submit the Spec to the CocoaPods repo?

**Pull request merged**
